### PR TITLE
Fs2 3

### PR DESCRIPTION
**Pull request by satabin**
Port fs2-data to fs2 3 and CE3.

This requires disneystreaming/weaver-test#157 to be merged and published first.

### CODE REVIEW

**Comment by keynmol** [comment]
(Responding as I saw your ref on our PR)

We've been releasing a few milestone versions for both CE2 and CE3 (note that CE3 artifacts are one minor version above CE2 ones): https://disneystreaming.github.io/weaver-test/docs/installation so you can give it a go :)

**Comment by satabin** [comment]
Thank you, I will upgrade to that version.

**Comment by keynmol** [comment]
There's some small source breaking changes, so if you have any questions about migration - I can help here :)

**Review by ybasket — APPROVED** [review]
Looks all good to me 👍

**Pull request merged**
