### PR TITLE
Auto derivation for csv-generic

### PR DESCRIPTION
**Pull request by ybasket**
Using the same technique as in pureconfig and circe. Once #10 is merged, support for cell decoders can be added as well.

Additionally, I added a small beautification to the file-based tests, relativizing the file paths to make the test output more readable.

### CODE REVIEW

**Comment by satabin** [comment]
Sadly enough it looks like I have to accept this 😭

**Comment by ybasket** [comment]
What’s the matter? Not a fan of auto-derivation or unhappy you couldn’t find something to improve?

**Comment by satabin** [comment]
The former.

**Comment by satabin** [comment]
I knew I shouldn’t have merged it :sob: https://travis-ci.com/satabin/fs2-data/builds/139190115

**Pull request merged**
